# Generated by Django 2.2.24 on 2022-03-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='temperature',
        ),
    ]
